### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by pereira49** [42Telecom/php-sdk-advanced-messaging-platform#1]
composer require fortytwo/php-sdk-advanced-messaging-platform

  [InvalidArgumentException]
  Could not find package fortytwo/php-sdk-advanced-messaging-platform at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-utoloader] [-a|--classmap-authoritative] [--] [<packages>]...

**Comment by sebastien-lemarinel** [comment]
Hello,

The SDK is currently in Release Candidate. So you can do:

`composer require fortytwo/php-sdk-advanced-messaging-platform:1.0.0-RC1`

Regards,
Sebastien.

**Comment by pereira49** [comment]
OK, thanks.
