### ISSUE TITLE
Setting SMS Destination Parameters

### ISSUE THREAD

**Issue by joshatdf** [42Telecom/php-sdk-advanced-messaging-platform#2]
Hi,

I'm attempting to use your library to send SMS messages using the _"Request with custom Key-Value replacements in message per destination"_ feature as defined here: https://www.fortytwo.com/apis/sms-gateway-rest-api/samples/#CustomKeyValueReplacements.

I'm a bit puzzled how to set the key=>value parameters using the library, as looking at the code it's expecting the parameters to be of type **string**.

`$destination->setParams($parameters);`

Am I missing something, or is this a bug in the library? 

I'll dynamically replace the message content per SMS destination on my end as a workaround, but would be awesome to be able to use this feature.

**Comment by sebastien-lemarinel** [comment]
Hi,

It's definitely a bug. I'm working on it and and push an update later today.

Regards,
Sebastien.

**Comment by sebastien-lemarinel** [comment]
I just published a new Release Candidate (RC5). You can pass parameters as a key/value array now.

**Comment by joshatdf** [comment]
Thanks Sebastien—Changes look good and it's now working great with parameters set as an array. Great library btw, looks really well written 😄.
